import type { Metadata } from "next";
import "@/styles/index.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-primary">
        <main className="flex-grow container mx-auto max-w-4xl pt-12 pb-12 px-0">{children}</main>
      </body>
    </html>
  );
}
